---
title: "Group 14 Project"
author: "Edison Cheah, Dev Nair, Eldrick Chen"
date: "04/07/2026"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r better_notation}
 options(scipen = 999)
```

```{r}
library(dplyr)

# Load in March Madness datasets
original_dataset <- read.csv("cbb.csv")
large_dataset <- read.csv("march-madnesss-historical-data.csv")

# DATA CLEANING 1: Purge all non-tournament teams from dataset
original_dataset <- original_dataset %>%
  filter(!is.na(POSTSEASON) & POSTSEASON != "NA" & POSTSEASON != "N/A")

original_dataset$TEAM <- gsub("[^A-Za-z ]", "", original_dataset$TEAM)
large_dataset$Team <- gsub("[^A-Za-z ]", "", large_dataset$Team)

large_dataset$Team <- gsub("State", "St.", large_dataset$Team)

large_dataset$Team[large_dataset$Team == "Brigham Young"] <- "BYU"
large_dataset$Team[large_dataset$Team == "FDU"] <- "Fairleigh Dickinson"
large_dataset$Team[large_dataset$Team == "GardnerWebb"] <- "Gardner Webb"
large_dataset$Team[large_dataset$Team == "Louisiana"] <- "Louisiana Lafayette"
large_dataset$Team[large_dataset$Team == "Louisiana St."] <- "LSU"
large_dataset$Team[large_dataset$Team == "Loyola IL"] <- "Loyola Chicago"
large_dataset$Team[large_dataset$Team == "Mount St. Marys"] <- "Mount St. Mary's"
large_dataset$Team[large_dataset$Team == "North Carolina AT"] <- "North Carolina A&T"
large_dataset$Team[large_dataset$Team == "Prairie View"] <- "Prairie View A&M"
large_dataset$Team[large_dataset$Team == "Saint Josephs"] <- "Saint Joseph's"
large_dataset$Team[large_dataset$Team == "Saint Marys"] <- "Saint Mary's"
large_dataset$Team[large_dataset$Team == "Saint Peters"] <- "Saint Peter's"
large_dataset$Team[large_dataset$Team == "St Johns NY"] <- "St. John's"
large_dataset$Team[large_dataset$Team == "Stephen F Austin"] <- "Stephen F. Austin"
large_dataset$Team[large_dataset$Team == "Texas AM"] <- "Texas A&M"
large_dataset$Team[large_dataset$Team == "Texas AMCorpus Christi"] <- "Texas A&M Corpus Chris"

# Create list of unique teams
original_teams_unique <- sort(unique(original_dataset$TEAM))
large_teams_unique <- sort(unique(large_dataset$Team))
merged_teams_unique <- intersect(original_teams_unique, large_teams_unique)

large_dataset <- large_dataset %>%
  filter(Team %in% merged_teams_unique & !(Year %in% c(2012, 2024)))
original_dataset <- original_dataset %>%
  filter(TEAM %in% merged_teams_unique & !(YEAR %in% c(2012, 2024)))

# DATA CLEANING 2: Standardize 
merged_dataset <- merge(original_dataset,
                        large_dataset[, c("Team", "Year", "OppO", "OppD", "Made.Round.of.16")], 
                        by.x = c("TEAM", "YEAR"),
                        by.y = c("Team", "Year")
                        )

# DATA CLEANING 3: Create new variable NetRtg (net rating)
merged_dataset$NetRtg <- merged_dataset$OppO - merged_dataset$OppD
```